import raw from "@/data/catalog.json";

/* Shape of src/data/catalog.json. That file is generated by
   `npm run catalog` (scripts/import-catalog.mjs); don't edit it by hand. */

export type CatalogImage = {
  src: string;
  width: number;
  height: number;
  /** Tiny base64 WebP shown blurred while the photo loads. Optional
      (DB-served products don't carry one; the image just loads without it). */
  blur?: string;
};

export type CatalogProduct = {
  id: string;
  /** The product code customers quote. Optional for DB-served products. */
  code?: number;
  slug: string;
  name: string;
  price: number;
  mrp?: number;
  category?: string;
  collection?: string;
  colour?: string;
  fabric?: string;
  care?: string;
  description?: string;
  sizes: string[];
  tag?: string;
  inStock: boolean;
  featured: boolean;
  images: CatalogImage[];
};

export type Catalog = {
  version: number;
  generatedAt: string | null;
  products: CatalogProduct[];
  site: {
    hero: CatalogImage | null;
    story: CatalogImage | null;
    looks: CatalogImage[];
  };
};

export const catalog = raw as unknown as Catalog;
