import raw from "@/data/catalog.json";

/* Shape of src/data/catalog.json. That file is generated by
   `npm run catalog` (scripts/import-catalog.mjs); don't edit it by hand. */

export type CatalogImage = {
  src: string;
  width: number;
  height: number;
  /** Tiny base64 WebP shown blurred while the photo loads. */
  blur: string;
};

export type CatalogProduct = {
  id: string;
  /** The photo number, e.g. 7 for 7.jpg. Doubles as the product code customers quote. */
  code: number;
  slug: string;
  name: string;
  price: number;
  mrp?: number;
  category?: string;
  collection?: string;
  colour?: string;
  fabric?: string;
  care?: string;
  description?: string;
  sizes: string[];
  tag?: string;
  inStock: boolean;
  featured: boolean;
  images: CatalogImage[];
};

export type Catalog = {
  version: number;
  generatedAt: string | null;
  products: CatalogProduct[];
  site: {
    hero: CatalogImage | null;
    story: CatalogImage | null;
    looks: CatalogImage[];
  };
};

export const catalog = raw as unknown as Catalog;
